### ISSUE TITLE
Missing `yaml-static` dep

### ISSUE THREAD

**Issue by kimburgess** [PlaceOS/core#108]
**Describe the bug**
`yaml-static` was [dropped from the Dockerfile recently](https://github.com/PlaceOS/core/commit/5dc0884444fc00392a85cac704c7928b1a2d165a#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557L19) resulting in a borked build.

**Your environment**
https://github.com/PlaceOS/PlaceOS/actions/runs/983685529

**Additional context**
Background on why it is needed: https://github.com/crystal-lang/distribution-scripts/issues/84

**Comment by caspiano** [comment]
Closed by b92db917617c2bb78de4d86f24dd688c8796cb69
