### ISSUE TITLE
orphaned module is still running but cannot be retrieved

### ISSUE THREAD

**Issue by w-le** [PlaceOS/core#139]
in core 1.2109.1,

I can see this still recurring in logs:
```
level=[E] time=2021-09-24T05:49:40Z program=drivers_place_bookings_7e1d570b7bc025a85f0085370ea644da657477d5_driver-Cd-73hdTTg source=mod-CerxbEn4I9 message="in scheduled task on Place::Bookings"
undefined method 'list_events' for Calendar_1 (driver index unavailable) (Exception)
  from repositories/drivers/lib/placeos-driver/src/placeos-driver/proxy/driver.cr:128:7 in '__exec_request__'
  from /usr/share/crystal/src/string/builder.cr:28:5 in '???'
  from repositories/drivers/drivers/place/bookings.cr:166:14 in 'poll_events'
```
Note **source=mod-CerxbEn4I9** from above snippet

Yet when I attempt to use backoffice I lookup that module by ID, it's a 404:
```
Request URL: https://REDACTED/api/engine/v2/modules/mod-CerxbEn4I9
Request Method: GET
Status Code: 404
```

Not sure how this situation occurred, maybe a System was deleted or something? @jeremyw24 might be able to provide more info. I can provide access to the system's db and logs.

**Comment by caspiano** [comment]
A temporary solution would be to kill the driver process of the module.
When the modules are reloaded, the orphan will not be loaded.
