### ISSUE TITLE
Improve driver reload process

### ISSUE THREAD

**Issue by caspiano** [PlaceOS/core#150]
**Is your feature request related to a problem? Please describe.**

Often, if a driver fails to load, the reason for the failure is not obvious. Related to #136

This leads to `protocol manager missing` logs because modules are loaded onto unstarted drivers.

**Describe the solution you'd like**

We should attempt to reload the driver when a `protocol manager missing` error occurs, where possible.

**Comment by stakach** [comment]
somewhat related to this, if a process exits unceremoniously (from cores perspective)
then it is never re-launched

however if it is killed via the cluster UI in backoffice / the core API then the process does re-launch successfully

**Comment by caspiano** [comment]
Potentially resolved by https://github.com/PlaceOS/driver/pull/134

**Comment by caspiano** [comment]
If a load fails because of a missing binary, this should be logged clearly.
Where possible, the reason why the module failed to start should be displayed.
