### ISSUE TITLE
Saving driver connected state in the database

### ISSUE THREAD

**Issue by stakach** [PlaceOS/core#21]
Having this status saved in the database is useful for monitoring purposes.
A major pitfall of the ruby version was handling rapid connect / disconnect of samsung devices so we'd want to limit the impact this can have on the database.

My thoughts on implementation are
* The core responsible for the module, manages the modules connected state in the database
* Limit the number of writes

This could mean:
* subscribe to the connected status of each running module
* track changes locally in a hash `@update_connected = {} of String => Bool`
  (mod_id => conn_state)
* remove anything in that hash that changes back
  * db state is `true`
  * connected changed to `false` => `@update_connected[mod_id] = false`
  * connected changed to `true` again => `@update_connected.delete(mod_id)`
* every 5 seconds bulk update the database if there are any entries in `@update_connected`

Looks like the write can occur in a single request: https://stackoverflow.com/questions/21488489/bulk-update-in-rethinkdb

**Comment by caspiano** [comment]
Closing as per discussion.
