### ISSUE TITLE
When branch is deleted on origin, and then later a new branch is created with same name, core fails to switch to and pull that new branch

### ISSUE THREAD

**Issue by w-le** [PlaceOS/core#235]
When branch is deleted on origin, and then later a new branch is created with same name, core fails to switch to and pull that new branch

When attempting to update a Driver from that new branch in backoffice, the list of `commits` returns by api/core is [], making it impossible to update the driver to the new commit.

**Comment by chillfox** [comment]
it needs to do a `git reset --hard origin/BRANCH_NAME` after the fetch

**Comment by chillfox** [comment]
Tried running through the git commands the code uses for `/api/core/v1/drivers/:file_name` with a test repo and deleting/recreating the remote branch. And that bit works as expected.

**Comment by chillfox** [comment]
Tried creating a test driver and deleting/recreating branches on GitHub, but I can't replicate this. Is it still an issue?
