### ISSUE TITLE
Driver is not updated when recompiled

### ISSUE THREAD

**Issue by grkek** [PlaceOS/core#244]
Recompilation, Update of a commit hash and any change made to the driver which can cause driver recompilation does not update the running instance with the latest version of the code.

Example can be observed in the PlaceOS development instance in the GSA ISE Edge Testing system, there should be more than two functions available to the interface.

**Comment by stakach** [comment]
this a bug on edge core?
I'll prioritise resolving this

**Comment by grkek** [comment]
> this a bug on edge core? I'll prioritise resolving this
> 
> Workaround is to delete the module and then add it back again once the new version is compiled

The workaround was discovered by me as well, it is a bit tiresome when it doesn't fetch the commits/drivers because of no reason what so ever.
