### ISSUE TITLE
Combine primary and edge builds into single Dockerfile

### ISSUE THREAD

**Issue by KimBurgess** [PlaceOS/core#62]
To support simpler builds following the merge of `feat/edge`, it would greatly simply external build tooling to use a build arg to designate between core and edge image builds.

There is a extremely clean pattern that would support this outlined here: https://stackoverflow.com/a/60820156.

This should also help remove duplication from the current dual Dockerfile setup.

**Comment by caspiano** [comment]
@KimBurgess any reason for reopening?

**Comment by KimBurgess** [comment]
None. Possibly from Zenhub - I updated so task state there around that time.
