### ISSUE TITLE
Some Drivers placeos/drivers fail to (re)compile

### ISSUE THREAD

**Issue by w-le** [PlaceOS/core#76]
(not urgent)
was able to reproduce the exact same symptom and error message at 
- 1 client site UAT instance and 
- 1 internal partner-environment instance at https://placeos-dev.aca.im/backoffice/#/drivers/driver-GAhbPNlItx5/about

1. A driver that exists in a private git repo forked from placeos/drivers was previously able to compile/recompile without any issue (using a version of core older than 4 weeks)

2. placeos/core is now updated to current `edge`

3. Trigger a recompile of the driver from (1): 
  - compilation fails, core container errors with:
```
 > 2 |   require "placeos-driver"
Error: can't find file 'placeos-driver'

If you're trying to require a shard:
- Did you remember to run `shards install`?
- Did you make sure you're running the compiler in the same directory as your shard.yml?
 message=processing failed
failed to compile DNB Visitor Mailer from dnb-drivers: In src/build.cr:1:1
```

4. A potentially related symptom: in backoffice/repositories, Pull on the the private git repo now fails after 60s, with a HTTP408. Other git driver repos are able to pull OK.
no msgs in core logs
api log entry is:
```
level=INFO time=2021-02-17T09:58:56Z source=action-controller repository_id=repo-GAgrqYBOJVW user_id=user-GEaJQS76HJn client_ip=61.10.28.243 request_id=b34986f0-d6f8-4f33-ad52-b9c60f4b8f07 event=response method=POST path=/api/engine/v2/repositories/repo-GAgrqYBOJVW/pull status=408 duration=20008.5894
Unhandled exception in spawn: Channel is closed (Channel::ClosedError)
  from app/lib/rethinkdb-orm/src/rethinkdb-orm/utils/changefeed.cr:31:13 in '->'
  from usr/share/crystal/src/primitives.cr:255:3 in 'run'
  from ???
```
I was able to `git pull` on the same repo manually without issues, by `sh`ing into the core container

**Comment by w-le** [comment]
new clues:
switched the affected placeos instance to placeo/core:f4ecbec2b712 (4wks old)
After core was discoverable by api, some drivers were able to compile and others were not:

- drives from private fork A of placeos/drivers were able to compile OK
- drives from private fork B of placeos/drivers were failed to compile/recompile (HTTP408 and same error msg as above)
- drivers from github.com/placeos/drivers repo failed to compile/recompile  (HTTP408 and same error msg as above)

So I think the issue may be related to the way compilation is handled when there are multiple git repos defined, as opposed to private vs public git repos.

**Comment by w-le** [comment]
Update:
1. The UAT client site mysteriously no longer suffers from the issue, despite there not having been any updates/changes to core or the affected driver.

2. The internal partner-environment instance still has the symptom and can be used for troubleshooting (it is not actively being used for any projects atm and can be safely fiddled with)
https://placeos-dev.aca.im/backoffice/#/drivers/driver-GAhbPNlItx5/about

**Comment by stakach** [comment]
it might have failed to `shards install` - which would cause the unable to find `placeos-driver`
the channel close issue is probably caused by a timeout, but might be something else @caspiano ideas?

**Comment by w-le** [comment]
closing this as efforts will instead focus on completing the new build service such that core will not be compiling drivers so this issue will not be encountered
