### ISSUE TITLE
core 1.2102.0: Deleting Modules from a System may result in redis system/ key to be out of sync with System's Module list

### ISSUE THREAD

**Issue by w-le** [PlaceOS/core#92]
I was able to reproduce a bug in `placeos-1.2102.0` running on placeos-dev where:
- use backoffice to delete a Module from a System
- redis key for system's module list becomes out of sync with database
  > this may cause Module exec requests to 404 even though the module exists an is running.
  In this example backoffice requests an exec on `Floorsense_1`, Core will lookup the module ID of Floorsense_1 using redis and try to fetch an already DELETED module ID instead of the correct Floorsense_1
```
# redis-cli HGETALL system/sys-GAg-Vlc~-LM
 1) "FloorsenseBookingSync/1"
 2) "mod-H28HWFdYTLJ"
 3) "VisitorMailer/1"
 4) "mod-GAhPmtjrwJg"
 5) "Mailer/1"
 6) "mod-GAgtt58lGvI"
 7) "LocationServices/1"
 8) "mod-GFEnGXq_Otl"
 9) "AreaManagement/1"
10) "mod-GFEoVQw_iqw"
11) "DeskBookings/1"
12) "mod-GFEoe0pFWtC"
13) "StaffAPI/1"
14) "mod-GFF2CmK9Es1"
15) "DeskBookingWebhook/1"
16) "mod-Gbdk0Vyqre4"
17) "Vergesense/1"
18) "mod-GVKhCo63OGM"
19) "VergesenseLocationService/1"
20) "mod-GeX9ytHj8NU"
21) "Floorsense/1"
22) "mod-H1uowkA4oiQ"
23) "Floorsense/2"
24) "mod-GnhfwKwpffn"
25) "FloorsenseLocationService/1"
26) "mod-GpQzIdyWvBX"
27) "Guests/1"
28) "mod-H1zfHOxOHsM"
#
```
https://placeos-dev.redacted.redacted/backoffice/#/systems/sys-GAg-Vlc~-LM/modules

![image](https://user-images.githubusercontent.com/10395560/113989190-c7c9e580-9882-11eb-8ca2-e8aea728d005.png)

**Comment by caspiano** [comment]
When @stakach stopped all the modules, and attempted to reproduce, the issue could not be replicated.

**Comment by w-le** [comment]
Note that the issue was experienced when deleting a module while all the moduels in the system were Running

**Comment by stakach** [comment]
@w-le : @caspiano is testing some fixes, should have a result tomorrow.

the issue occurs when a logic module didn't start properly (possibly compilation issue or settings issue)

there are two issues:

1. order of operations, should update hash before notifying logics
2. if a failure occurs it isn't handled properly (still trying to narrow this bit down)

so we're nearly at a resolution.
Good news is that you won't experience this issue if all the drivers in your system are functioning
