### ISSUE TITLE
Commit hashes from GitLab are weird

### ISSUE THREAD

**Issue by MrYuion** [PlaceOS/core#98]
**Describe the bug**
The commit hash returned by the API from a GitHub driver repo is returning unusual values.

**Screenshots**
![image(1)](https://user-images.githubusercontent.com/20103948/114814033-ad4dba00-9df6-11eb-8478-7182ac809cbd.png)

**Comment by caspiano** [comment]
This was the result of `GC_PRINT_STATS=1` in the environment, causing the garbage collection statistics of the `exec_from` binary to be interleaved with the STDOUT of the git commands.
